spring:
   autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
   datasource:
      url: "jdbc:mysql://localhost:3306/world?autoreconnect=true"
      username: "root"
      password: "password"
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
         max-wait: 10000
         max-active: 50
         test-on-borrow: true
   jpa:
     database-platform: org.hibernate.dialect.MySQL5Dialect
     hibernate:
       ddl-auto: create
     show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     shutdown:
        enabled: true
endpoint:
     shutdown:
        enabled: true
